on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: "Configure AWS Credentials" 
        # You may pin to the exact commit or the version.
        # uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          # The Amazon Resource Name (ARN) of the role to assume. Use the provided credentials to assume an IAM role and configure the Actions environment with the assumed role credentials rather than with the provided credentials.
          # role-to-assume: # optional
          # AWS Access Key ID. Provide this key if you want to assume a role using access keys rather than a web identity token.
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          # AWS Secret Access Key. Required if aws-access-key-id is provided.
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  
      - name: Log in to amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 314146337751.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Verify AWS CLI access
        run: aws sts get-caller-identity

      - name: Build Docker image
        run: docker build -t venkat_eeg_model_container.
        
      - name: Tag Docker image
        run: docker tag venkat_eeg_model_container:latest 939794682570.dkr.ecr.us-east-1.amazonaws.com/venkat_eeg_model_container:latest

      - name: Push Docker image to ECR
        run: docker push 939794682570.dkr.ecr.us-east-1.amazonaws.com/venkat_eeg_model_container:latest

  #deploy:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy to ECS
  #      run: |
  #        aws ecs update-service --cluster <cluster-name> --service <service-name> --force-new-deployment
  #      env:
  #        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
